# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###########################################################################
# Example: Soft-body demo (box | sphere, with optional inflation).
#
# Merged replacement for the four original primitive examples:
#   bouncing_box, bouncing_sphere, inflatable_box, inflatable_sphere.
#
# Loads a tetrahedral FEM primitive (``assets/<shape>/<shape>.usda``,
# generated by ``third_party/newton-mesh-tools``) onto a bouncy ground
# plane and drives it with :class:`newton.solvers.SolverInflatable`. With
# ``--pressure-mode off`` the solver runs at a fixed unit volume ratio
# (plain Neo-Hookean FEM); with ``--pressure-mode on`` a GUI slider drives
# isotropic inflation via :meth:`SolverInflatable.set_pressure` and the
# rest configuration scales by ``cbrt(p)`` each frame.
#
# Command: uv run -m newton.examples inflatable_demo
###########################################################################

from __future__ import annotations

import argparse
import os

import numpy as np
import warp as wp

import newton
import newton.examples

from ._usd_asset import load_asset

# Per-(shape, pressure_mode) default tuning. The (sphere, off) entry
# preserves the bouncing-ball tuning the standalone bouncing_sphere
# example used; everything else uses the "standard" box-style tuning
# shared by the other three originals.
_PRESETS = {
    ("box", False): dict(
        initial_height=0.5, mass=1.0, k_mu=1.0e5, k_lambda=1.0e5,
        k_damp=1.0, substeps=10, particle_radius=0.008,
        soft_contact_ke=5.0e4, soft_contact_kd=500.0, soft_contact_kf=5.0e4, soft_contact_mu=0.9,
        particle_ke=1.0e5, particle_kd=1.0,
        extra_solver_kwargs={},
        test_z_pad=1.0,
    ),
    ("sphere", False): dict(
        initial_height=2.5, mass=0.5, k_mu=2.0e5, k_lambda=2.0e5,
        k_damp=0.5, substeps=8, particle_radius=0.015,
        soft_contact_ke=5.0e4, soft_contact_kd=2000.0, soft_contact_kf=1.0e4, soft_contact_mu=0.8,
        particle_ke=None, particle_kd=None,
        extra_solver_kwargs=dict(
            use_constraint_contacts=True,
            linear_solver_maxiter=100,
            contact_max_velocity=15.0,
            contact_max_correction=0.015,
        ),
        test_z_pad=1.0,
    ),
    ("box", True): dict(
        initial_height=0.5, mass=1.0, k_mu=1.0e5, k_lambda=1.0e5,
        k_damp=1.0, substeps=10, particle_radius=0.008,
        soft_contact_ke=5.0e4, soft_contact_kd=500.0, soft_contact_kf=5.0e4, soft_contact_mu=0.9,
        particle_ke=1.0e5, particle_kd=1.0,
        extra_solver_kwargs={},
        test_z_pad=2.0,
    ),
    ("sphere", True): dict(
        initial_height=0.5, mass=1.0, k_mu=1.0e5, k_lambda=1.0e5,
        k_damp=1.0, substeps=10, particle_radius=0.008,
        soft_contact_ke=5.0e4, soft_contact_kd=500.0, soft_contact_kf=5.0e4, soft_contact_mu=0.9,
        particle_ke=1.0e5, particle_kd=1.0,
        extra_solver_kwargs={},
        test_z_pad=1.0,
    ),
    # Baymax: dense ~39k-tet character mesh. Stiffer Lamé parameters and
    # heavier substep count vs. box/sphere because the larger element count
    # would otherwise produce visible jitter under pressure ramps. Density
    # 1000 (vs. unit mass) so contact impulses don't shove the body off the
    # ground during inflation. The standalone soft_baymax example always
    # used pressure mode; the (baymax, False) preset shares the same tuning
    # for symmetry with box/sphere.
    ("baymax", False): dict(
        initial_height=0.45, mass=1000.0, k_mu=8.0e5, k_lambda=8.0e5,
        k_damp=2.0, substeps=24, particle_radius=0.008,
        soft_contact_ke=5.0e4, soft_contact_kd=500.0, soft_contact_kf=5.0e4, soft_contact_mu=0.9,
        particle_ke=1.0e5, particle_kd=1.0,
        extra_solver_kwargs={},
        test_z_pad=1.0,
    ),
    ("baymax", True): dict(
        initial_height=0.45, mass=1000.0, k_mu=8.0e5, k_lambda=8.0e5,
        k_damp=2.0, substeps=24, particle_radius=0.008,
        soft_contact_ke=5.0e4, soft_contact_kd=500.0, soft_contact_kf=5.0e4, soft_contact_mu=0.9,
        particle_ke=1.0e5, particle_kd=1.0,
        extra_solver_kwargs={},
        test_z_pad=2.0,
    ),
}


def _default_asset_path(shape: str) -> str:
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets", shape, f"{shape}.usda")


def _coalesce(override, preset_value):
    return preset_value if override is None else override


class Example:
    """Soft-body demo with selectable shape and optional inflation.

    Args:
        shape: ``"box"`` or ``"sphere"`` -- selects the bundled asset.
        pressure_mode: When True, exposes a GUI slider that drives
            :meth:`newton.solvers.SolverInflatable.set_pressure` and lets
            ``max_volume_ratio`` exceed 1.0 so the body inflates.
        Remaining args default from a per-(shape, pressure_mode) preset
        and can be overridden individually via CLI flags.
    """

    def __init__(
        self,
        viewer,
        args=None,
        shape: str = "box",
        pressure_mode: bool = False,
        asset_path: str | None = None,
        initial_height: float | None = None,
        mass: float | None = None,
        k_mu: float | None = None,
        k_lambda: float | None = None,
        k_damp: float | None = None,
        gravity: float = 9.81,
        substeps: int | None = None,
        max_pressure: float = 5.0,
        pressure_rate: float = 0.05,
        debug_interval: int = 0,
    ):
        shape = str(shape).lower()
        if shape not in ("box", "sphere", "baymax"):
            raise ValueError(f"shape must be 'box', 'sphere', or 'baymax', got {shape!r}")
        self.shape = shape
        self.pressure_mode = bool(pressure_mode)
        preset = _PRESETS[(shape, self.pressure_mode)]

        self.viewer = viewer
        self.fps = 60
        self.frame_dt = 1.0 / self.fps
        self.sim_substeps = int(_coalesce(substeps, preset["substeps"]))
        self.sim_dt = self.frame_dt / self.sim_substeps
        self.sim_time = 0.0
        self.initial_height = float(_coalesce(initial_height, preset["initial_height"]))
        self.max_pressure = float(max_pressure)
        self.pressure_rate = float(pressure_rate)
        # Slider writes target_pressure; current_pressure chases it at
        # pressure_rate / frame. Direct slider-to-solver jumps would scale
        # the FEM rest config by cbrt(p) in one frame and blow up the
        # implicit solve, so we rate-limit here even though the solver
        # clamps to [1.0, max_volume_ratio].
        self.target_pressure = 1.0
        self.current_pressure = 1.0
        self._debug_interval = max(0, int(debug_interval))
        self._frame_idx = 0
        self._rest_particle_q_np: np.ndarray | None = None

        path = asset_path or _default_asset_path(shape)
        if not os.path.isfile(path):
            raise FileNotFoundError(
                f"{shape.capitalize()} asset not found at {path}. Regenerate with "
                "third_party/newton-mesh-tools/scripts/generate_assets.py"
            )
        asset = load_asset(path)
        verts = asset["vertices"]
        tets = asset["tets"]

        mass_val = float(_coalesce(mass, preset["mass"]))
        builder = newton.ModelBuilder()
        builder.add_ground_plane(cfg=newton.ModelBuilder.ShapeConfig(ke=5e5, kd=1e3, kf=1e4, mu=0.5))
        builder.add_soft_mesh(
            pos=wp.vec3(0.0, 0.0, self.initial_height),
            rot=wp.quat_identity(),
            vel=wp.vec3(0.0, 0.0, 0.0),
            vertices=verts,
            indices=tets.flatten(),
            scale=1.0,
            density=mass_val,
            k_mu=float(_coalesce(k_mu, preset["k_mu"])),
            k_lambda=float(_coalesce(k_lambda, preset["k_lambda"])),
            k_damp=float(_coalesce(k_damp, preset["k_damp"])),
        )

        self.model = builder.finalize()
        self.model.set_gravity((0.0, 0.0, -float(gravity)))

        self.model.soft_contact_ke = preset["soft_contact_ke"]
        self.model.soft_contact_kd = preset["soft_contact_kd"]
        self.model.soft_contact_kf = preset["soft_contact_kf"]
        self.model.soft_contact_mu = preset["soft_contact_mu"]
        if preset["particle_ke"] is not None:
            self.model.particle_ke = preset["particle_ke"]
        if preset["particle_kd"] is not None:
            self.model.particle_kd = preset["particle_kd"]
        self.model.particle_radius = wp.array(
            np.full(self.model.particle_count, preset["particle_radius"], dtype=np.float32),
            dtype=wp.float32,
            device=self.model.device,
        )
        self._test_z_pad = float(preset["test_z_pad"])

        self.solver = newton.solvers.SolverInflatable(
            model=self.model,
            dt=self.sim_dt,
            mass=mass_val,
            max_volume_ratio=self.max_pressure if self.pressure_mode else 1.0,
            solver_type="bicgstab",
            **preset["extra_solver_kwargs"],
        )

        self.state_0 = self.model.state()
        self.state_1 = self.model.state()
        self.control = self.model.control()
        self.contacts = self.model.contacts()

        self.viewer.set_model(self.model)
        if hasattr(self.viewer, "show_particles"):
            self.viewer.show_particles = True

        if self._debug_interval > 0:
            self._rest_particle_q_np = self.state_0.particle_q.numpy().copy()

        self.capture()

    def capture(self) -> None:
        """Warm up kernels, snapshot initial state, then capture a CUDA graph.

        Warmup is mandatory: lazy Warp modules (``warp.optim.linear``,
        sparse BSR) get loaded on first use, and if that happens inside
        the :class:`wp.ScopedCapture` block the capture fails. In pressure
        mode, pressure is refreshed each :meth:`step` via
        :meth:`SolverInflatable.set_pressure` which edits device buffers,
        so the slider takes effect on the next captured launch without a
        re-capture.
        """
        self.graph = None
        if not wp.get_device().is_cuda:
            return
        snap_0 = self.model.state(); snap_0.assign(self.state_0)
        snap_1 = self.model.state(); snap_1.assign(self.state_1)
        try:
            self.simulate()
            wp.synchronize_device()
        except Exception as exc:
            print(f"   [capture] warmup failed ({exc}); running eager.", flush=True)
            self.state_0.assign(snap_0)
            self.state_1.assign(snap_1)
            return
        self.state_0.assign(snap_0)
        self.state_1.assign(snap_1)
        try:
            with wp.ScopedCapture() as capture:
                self.simulate()
            self.graph = capture.graph
        except Exception as exc:
            print(f"   [capture] ScopedCapture failed ({exc}); running eager.", flush=True)
            self.state_0.assign(snap_0)
            self.state_1.assign(snap_1)
            self.graph = None

    def simulate(self) -> None:
        if self.pressure_mode:
            self.solver.set_pressure(self.current_pressure)
        for _ in range(self.sim_substeps):
            self.state_0.clear_forces()
            self.viewer.apply_forces(self.state_0)
            self.model.collide(self.state_0, self.contacts)
            self.solver.step(self.state_0, self.state_1, self.control, self.contacts, self.sim_dt)
            self.state_0, self.state_1 = self.state_1, self.state_0

    def step(self) -> None:
        if self.pressure_mode:
            # Chase the slider target at pressure_rate per frame so the
            # FEM rest configuration never scales by more than cbrt(step)
            # in one frame. Snap once we're within one rate step.
            delta = self.target_pressure - self.current_pressure
            if abs(delta) <= self.pressure_rate:
                self.current_pressure = self.target_pressure
            else:
                self.current_pressure += self.pressure_rate * (1.0 if delta > 0.0 else -1.0)
        if self.graph is not None:
            if self.pressure_mode:
                self.solver.set_pressure(self.current_pressure)
            wp.capture_launch(self.graph)
            if self.sim_substeps % 2 == 1:
                self.state_0, self.state_1 = self.state_1, self.state_0
        else:
            self.simulate()
        self.sim_time += self.frame_dt

        self._frame_idx += 1
        if self._debug_interval > 0 and self._frame_idx % self._debug_interval == 0:
            self._dump_debug_state()

    def _dump_debug_state(self) -> None:
        """Print one line of particle bbox / NaN / drift / pressure state.

        Cheap host-side numpy round-trip. Intended for catching slow
        divergence before the implicit solve goes NaN. Off by default;
        gated by ``--debug-interval > 0``.
        """
        try:
            q = self.state_0.particle_q.numpy()
            nan_n = int(np.isnan(q).any(axis=1).sum())
            parts = [f"[dbg t={self.sim_time:7.3f}s f={self._frame_idx:6d}]"]
            if nan_n:
                parts.append(f"NaN={nan_n}/{q.shape[0]}")
            else:
                qmin = q.min(axis=0); qmax = q.max(axis=0); bbox = qmax - qmin
                parts.append(
                    "qmin=({:+.3f},{:+.3f},{:+.3f}) qmax=({:+.3f},{:+.3f},{:+.3f}) "
                    "bbox=({:.3f},{:.3f},{:.3f})".format(
                        qmin[0], qmin[1], qmin[2],
                        qmax[0], qmax[1], qmax[2],
                        bbox[0], bbox[1], bbox[2],
                    )
                )
                if self._rest_particle_q_np is not None:
                    drift = np.linalg.norm(q - self._rest_particle_q_np, axis=1)
                    parts.append(
                        f"drift max={float(drift.max()):.4f} mean={float(drift.mean()):.4f}"
                    )
            if self.pressure_mode:
                parts.append(f"pres cur={self.current_pressure:.3f} tgt={self.target_pressure:.3f}")
            print(" ".join(parts), flush=True)
        except Exception as exc:
            print(f"[inflatable_demo][dbg] dump failed: {exc}", flush=True)

    def gui(self, ui) -> None:
        """ImGui side-panel slider for the target pressure ratio."""
        if not self.pressure_mode:
            return
        changed, value = ui.slider_float("pressure", self.target_pressure, 1.0, self.max_pressure)
        if changed:
            self.target_pressure = float(value)

    def render(self) -> None:
        self.viewer.begin_frame(self.sim_time)
        self.viewer.log_state(self.state_0)
        self.viewer.log_contacts(self.contacts, self.state_0)
        self.viewer.end_frame()

    def test_final(self) -> None:
        p_lower = wp.vec3(-2.0, -2.0, -0.2)
        p_upper = wp.vec3(2.0, 2.0, self.initial_height + self._test_z_pad)
        newton.examples.test_particle_state(
            self.state_0,
            f"{self.shape} particles stay in workspace",
            lambda q, _qd: newton.math.vec_inside_limits(q, p_lower, p_upper),
        )


if __name__ == "__main__":
    parser = newton.examples.create_parser()
    parser.add_argument("--shape", type=str, default="box", choices=("box", "sphere", "baymax"),
                        help="Which bundled mesh to load (assets/<shape>/<shape>.usda).")
    parser.add_argument("--pressure-mode", action=argparse.BooleanOptionalAction, default=False,
                        help="Expose an ImGui slider that drives SolverInflatable.set_pressure.")
    parser.add_argument("--asset", type=str, default=None, help="Override the bundled .usda path.")
    parser.add_argument("--initial-height", type=float, default=None,
                        help="Drop height [m]. Defaults from (shape, pressure-mode) preset.")
    parser.add_argument("--mass", type=float, default=None,
                        help="Density / mass scale. Defaults from preset.")
    parser.add_argument("--k_mu", type=float, default=None,
                        help="Shear modulus [Pa]. Defaults from preset.")
    parser.add_argument("--k_lambda", type=float, default=None,
                        help="First Lamé parameter [Pa]. Defaults from preset.")
    parser.add_argument("--k_damp", type=float, default=None,
                        help="FEM damping coefficient. Defaults from preset.")
    parser.add_argument("--gravity", type=float, default=9.81, help="Gravity magnitude [m/s²].")
    parser.add_argument("--substeps", type=int, default=None,
                        help="Sim substeps per frame. Defaults from preset.")
    parser.add_argument("--max-pressure", type=float, default=5.0,
                        help="Maximum volume ratio in pressure mode.")
    parser.add_argument("--debug-interval", type=int, default=0,
                        help="When > 0, print particle bbox / drift / NaN "
                             "count / pressure every N frames. 0 = off.")
    parser.add_argument("--pressure-rate", type=float, default=0.05,
                        help="Max change of applied pressure per frame.")

    viewer, args = newton.examples.init(parser)

    example = Example(
        viewer=viewer,
        args=args,
        shape=args.shape,
        pressure_mode=bool(args.pressure_mode),
        asset_path=args.asset,
        initial_height=args.initial_height,
        mass=args.mass,
        k_mu=args.k_mu,
        k_lambda=args.k_lambda,
        k_damp=args.k_damp,
        gravity=args.gravity,
        substeps=args.substeps,
        max_pressure=args.max_pressure,
        pressure_rate=args.pressure_rate,
        debug_interval=args.debug_interval,
    )

    newton.examples.run(example, args)
